"""added admin props to user.

Revision ID: 7c93ed621c94
Revises: 459d815c891c
Create Date: 2023-09-10 14:48:08.209045
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c93ed621c94"
down_revision: Union[str, None] = "459d815c891c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_staff", sa.Boolean(), server_default="FALSE", nullable=False))
    op.add_column("user", sa.Column("is_superuser", sa.Boolean(), server_default="FALSE", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_superuser")
    op.drop_column("user", "is_staff")
    # ### end Alembic commands ###
